### ISSUE TITLE
Embed images with https

### ISSUE THREAD

**Issue by Trikolon** [jamesinc/imgur-upload#3]
My forum is full SSL and when users upload images they get embedded with http only. Could you fix this please?

**Comment by AdamCarballo** [comment]
I was about to post the same.
I'm not sure if Imgur returns images with HTTPS. Their API documentation just has one key (link) to return the image link as an string (HTTP).

I "fixed" the issue by replacing the "http" of the returned string by "https", since Imgur will serve the image also in HTTPS.

Search for the variable `data.link` inside `imgurupload.js` and add `.replace("http", "https")` to the end. An example:

```
case "bbcode" :
response = '[img]' + data.link.replace("http", "https") + '[/img]';
break;
```

Remember that the plugin is using the minified version. You will need to re-minify the file or use `imgurupload.js` directly.

**Comment by jamesinc** [comment]
@Trikolon @AdamEC yes, I agree it makes more sense to use https. @AdamEC the way you've done it may lead to issues if the image filename contains the string "https". I'll publish an update for this issue in a couple minutes.

**Comment by AdamCarballo** [comment]
@jamesinc You are right, I didn't thought about that!
